version: '3'

services:
  db:
    container_name: escola-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  escola-api:
    container_name: escola-api
    build: ./escola
    command: dockerize -wait tcp://db:5432 -timeout 300s -wait-retry-interval 2s /app/start.sh
    volumes:
      - ./escola:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SUPERUSER_USER=admin
      - DJANGO_SUPERUSER_PASSWORD=abc123
      - DJANGO_SUPERUSER_EMAIL=admin@example.com

